### ISSUE TITLE
using custom ext in extras does not work when running diff. 

### ISSUE THREAD

**Issue by scoutman57** [Tekill/env-diff#1]
add to composer
"scripts": {
    "post-update-cmd": "LF\\EnvDiff\\Composer\\ScriptHandler::actualizeEnv"
},"extra": {
        "lf-env-diff": [
            {
                "dist": ".env.example",
                "target": ".env"
            }
        ]
    }

run composer update 
You get an error that .env.dist does not exist.

**Comment by Tekill** [comment]
Hi! 

Thank you for feedback

**Comment by Tekill** [comment]
Fixed, working version is `1.0.3`
